### ISSUE TITLE
Couldn't find preset "es2015" relative to directory

### ISSUE THREAD

**Issue by WebTerminator** [gokulkrishh/how-to-setup-webpack-2#1] opened 2017-02-03 15:53 UTC
I am getting the following error:

ERROR in (webpack)/buildin/module.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory 

after having installed:
$ npm install --save-dev babel-loader babel-core babel-preset-es2015

and ran webpack-dev-server

**Comment by gokulkrishh** [comment] 2017-02-04 04:44
Weird issue. @WebTerminator Are you using `windows` or `mac` or `linux`. ??

**Comment by timcan** [comment] 2017-02-20 17:19
+1 (same problem on mac)

**Comment by gokulkrishh** [comment] 2017-02-22 07:54
@timcan @WebTerminator Looking into it. Thanks for reporting 👍

**Comment by radiocity** [comment] 2017-05-04 09:04
Replace
```js
rules: [
    {
      test: /\.js$/, //Check for all js files
      use: [{
        loader: 'babel-loader',
        options: { presets: ['es2015'] }
      }]
    }
  ]
```
with 
```js
rules: [ {
    test: /\.js$/,
    loader: "babel-loader",
    query: {
        presets: [ "babel-preset-es2015" ].map(require.resolve)
    }
} ];
```

**Comment by gokulkrishh** [comment] 2017-05-04 09:27
@radiocity Thanks for pointing it out 👍 I will update the readme 😀

**Comment by gokulkrishh** [comment] 2017-05-04 09:38
Closing this issue as the above snippet solved the problem @timcan @WebTerminator. Let me know if the issue is still there.

**Closed as completed by gokulkrishh** 2017-05-04 09:38 UTC
